all:
	g++ chess_e.c bitboards.c init.c hashkey.c board.c attack.c data.c io.c movegen.c validate.c makemove.c perft.c misc.c search.c pvtable.c evaluate.c uci.c  xboard.c -o animeme_2
	
clean:
	$(RM) chess.exe